=== berb/rest-doc-template/xsd/rest-api-doc.xsd
<?xml version="1.0"?>
<xsd:schema xmlns="http://www.ioexception.de/rest-api-doc"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ioexception.de/rest-api-doc"
	elementFormDefault="qualified">
	<xsd:element name="api">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string" />
				<xsd:element name="version" type="xsd:string" />
				<xsd:element name="author" type="xsd:string" />
				<xsd:element name="description" type="descriptionType" />
				<xsd:element name="baseuri" type="xsd:anyURI" />
				<xsd:element name="authentication">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="type" type="authType" minOccurs="0"
								maxOccurs="unbounded" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="resources" type="resourcesListType" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>


	<xsd:complexType name="resourcesListType">
		<xsd:sequence>
			<xsd:element name="resource" type="resourceType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="resourceType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="description" type="descriptionType" />
			<xsd:element name="path" type="uriPartType" minOccurs="0" />
			<xsd:sequence>
				<xsd:element name="operation" type="operationType"
					minOccurs="0" maxOccurs="unbounded" />

			</xsd:sequence>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="operationType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="description" type="descriptionType" />
			<xsd:element name="path" minOccurs="0" >
				<xsd:complexType >
					<xsd:complexContent>
						<xsd:extension base="uriPartType">
						<xsd:attribute use="optional" name="omitResourcePath" type="xsd:boolean" default="false"/>
						</xsd:extension>						
					</xsd:complexContent> 
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="formats">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="format" type="contentType"
							maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="request" type="requestType" />
			<xsd:element name="response" type="responseType" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="requestType">
		<xsd:sequence>
			<xsd:element name="method" type="httpmethodType" />
			<xsd:element name="authentication">
				<xsd:complexType>
					<xsd:attribute use="required" name="mandatory" type="xsd:boolean" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="entities" type="entityType" />

		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="responseType">
		<xsd:sequence>
			<xsd:element name="responses" type="answerType" />
			<xsd:element name="entities" type="entityType" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="entityType">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="entity" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="code" type="codeType" minOccurs="0" />
						<xsd:element name="description" type="xsd:string"
							minOccurs="0" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="returnsType">
		<xsd:sequence minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="return">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="language" type="xsd:string" />
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="httpstatuscodeType">
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:enumeration value="100" />
			<xsd:enumeration value="101" />
			<xsd:enumeration value="200" />
			<xsd:enumeration value="201" />
			<xsd:enumeration value="202" />
			<xsd:enumeration value="203" />
			<xsd:enumeration value="204" />
			<xsd:enumeration value="205" />
			<xsd:enumeration value="206" />
			<xsd:enumeration value="300" />
			<xsd:enumeration value="301" />
			<xsd:enumeration value="302" />
			<xsd:enumeration value="303" />
			<xsd:enumeration value="304" />
			<xsd:enumeration value="305" />
			<xsd:enumeration value="306" />
			<xsd:enumeration value="307" />
			<xsd:enumeration value="400" />
			<xsd:enumeration value="401" />
			<xsd:enumeration value="402" />
			<xsd:enumeration value="403" />
			<xsd:enumeration value="404" />
			<xsd:enumeration value="405" />
			<xsd:enumeration value="406" />
			<xsd:enumeration value="407" />
			<xsd:enumeration value="408" />
			<xsd:enumeration value="409" />
			<xsd:enumeration value="410" />
			<xsd:enumeration value="411" />
			<xsd:enumeration value="412" />
			<xsd:enumeration value="413" />
			<xsd:enumeration value="414" />
			<xsd:enumeration value="415" />
			<xsd:enumeration value="416" />
			<xsd:enumeration value="417" />
			<xsd:enumeration value="500" />
			<xsd:enumeration value="501" />
			<xsd:enumeration value="502" />
			<xsd:enumeration value="503" />
			<xsd:enumeration value="504" />
			<xsd:enumeration value="505" />
		</xsd:restriction>
	</xsd:simpleType>


	<xsd:simpleType name="httpmethodType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="HEAD" />
			<xsd:enumeration value="GET" />
			<xsd:enumeration value="POST" />
			<xsd:enumeration value="PUT" />
			<xsd:enumeration value="DELETE" />
		</xsd:restriction>
	</xsd:simpleType>


	<xsd:simpleType name="authType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Basic Authentication" />
			<xsd:enumeration value="Digest Authentication" />
			<xsd:enumeration value="OAuth" />
		</xsd:restriction>
	</xsd:simpleType>


	<xsd:simpleType name="contentType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="application/json" />
			<xsd:enumeration value="text/xml" />
			<xsd:enumeration value="text/plain" />
			<xsd:enumeration value="n/a" />
			<xsd:enumeration value="application/atom+xml" />
			<xsd:enumeration value="application/vnd.google-earth.kml+xml" />
			<xsd:enumeration value="varying" />
			
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="languageType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="js" />
			<xsd:enumeration value="xml" />
			<xsd:enumeration value="plain" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="codeType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute use="required" name="language" type="languageType" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="answerType">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="answer">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute use="required" name="code"
								type="httpstatuscodeType" />
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="uriPartType" mixed="true">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="param">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute use="required" name="description"
								type="xsd:string" />
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="descriptionType" mixed="true">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="b" type="xsd:string" minOccurs="0" />
			<xsd:element name="it" type="xsd:string" minOccurs="0" />
			<xsd:element name="tt" type="xsd:string" minOccurs="0" />
			<xsd:element name="code" type="codeType" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== berb/rest-doc-template/example/example.xml
<?xml version="1.0" encoding="UTF-8"?>

<api xmlns="http://www.ioexception.de/rest-api-doc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ioexception.de/rest-api-doc ../xsd/rest-api-doc.xsd ">
	<name>Foo Bar Example API</name>
	<version>v2</version>
	<author>John Doe</author>
	<description>The following document describe the RESTful API of the
		example service foo bar. </description>
	<baseuri>http://myapipath/v2</baseuri>
	<authentication>
		<type>Basic Authentication</type>
		<type>OAuth</type>
	</authentication>
	<resources>	
					
		<resource>
			<name>User</name>
			<description>This resource represents a user. </description>
			<path>/user/<param description="user ID">user-id</param></path>
			<operation>
				<name>Create a new user account</name>
				<description>Creates a new user account, if user registration is enabled.</description>
				<path omitResourcePath="true">/users</path>
				<formats><format>application/json</format></formats>
				<request>
					<method>POST</method>
					<authentication  mandatory="false" />
					<entities>
						<entity>
							<code language="js">
<![CDATA[{
	 "email" : "john@doe.net",
	 "username" : "John Doe"
}]]></code>
						</entity>						
					</entities>
				</request>
				<response>
					<responses>
						<answer code="201">User account has been created. The location header contains its URI.</answer>
						<answer code="400">The provided data are incomplete or invalid.</answer>
						<answer code="403">The service instance does not allow the creation of new user accounts.</answer>
						<answer code="409">The user account has not been created, because there already exists an account with matching parameters.</answer>
					</responses>
					<entities />										
				</response>
			</operation>	
			<operation>
				<name>Get user details</name>
				<description>Returns information about a registered user.</description>				
				<formats><format>application/json</format></formats>
				<request>
					<method>GET</method>
					<authentication mandatory="true" />
					<entities />
				</request>
				<response>
					<responses>
						<answer code="200">The data set is returned as the response entity.</answer>
						<answer code="404">There is no user with this user ID.</answer>
					</responses>
					<entities >
						<entity>
							<code language="js">
<![CDATA[{
	 "username" : "John Doe"
}]]></code>
							<description>The data returned when queried by another user.</description>
						</entity>
						<entity>
							<code language="js">
<![CDATA[{
	 "email" : "john@doe.net",
	 "username" : "John Doe"
}]]></code>
							<description>The data returned when queried by the user himself.</description>
						</entity>
					</entities>					
				</response>
			</operation>					
		</resource>
	</resources>
</api>
